// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CarM8_01.Data
{
    public partial class Carm8dataContext : DbContext
    {
        public Carm8dataContext()
        {
        }

        public Carm8dataContext(DbContextOptions<Carm8dataContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Vehicles> Vehicles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Vehicles>(entity =>
            {
                entity.HasKey(e => e.VehicleId);

                entity.HasIndex(e => e.VehicleId)
                    .HasName("UNQ_Vehicles_Id")
                    .IsUnique();

                entity.Property(e => e.VehicleId)
                    .HasColumnName("VehicleID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Color)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Engine)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.FuelCapacity)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Make)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Model)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.VehicleType)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Year)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}