// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace CarM8_01.Data
{
    public partial class Vehicles
    {
        public int VehicleId { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string VehicleType { get; set; }
        public string Color { get; set; }
        public string Engine { get; set; }
        public string Mileage { get; set; }
        public string FuelCapacity { get; set; }


    }
}